### PR TITLE
Fix trace log duration for all logging implementations

### PR DESCRIPTION
**Pull request by k-simons**
- The spec specifies that it should be in milliseconds, however right now we are emitting in nanoseconds
- This is because the Math.Round() just zeroes out the last 3 digits, we still need to divide to truncate them

This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48)

### CODE REVIEW

**Review by bmoylan — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48)* status: all files reviewed, 2 unresolved discussions (waiting on @k-simons)

*[a discussion](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LdtbnUkB6G-gr0K_YMx:-LdtbnUkB6G-gr0K_YMy:b-82t0nn) (no related file):*
Is it possible to test this?

---
___
*[wlog-glog/internal/marshalers/wtracing_spanmodel.go, line 58 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-Ldtbpt_435ZT6_0yFsO:-Ldtbpt_435ZT6_0yFsP:b-j9sopw) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/16af38a569d996e45bcb43940b9df82e6ed126e7/wlog-glog/internal/marshalers/wtracing_spanmodel.go#L58)):*
> ```Go
> 		_, _ = builder.WriteString(separator)
> 	}
> 	_, _ = builder.WriteString(fmt.Sprintf("%s: %d", trc1log.SpanDurationKey, int64(span.Duration.Round(time.Microsecond))/1e3))
> ```

I think `int64(span.Duration/time.Microsecond)` would do the same thing?

**Review by nmiyake — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48)* status: all files reviewed, 2 unresolved discussions (waiting on @k-simons and @ksimons)

*[a discussion](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LdtbnUkB6G-gr0K_YMx:-Ldtcuaf6tSrfAaoQtYw:bfnzm3e) (no related file):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Is it possible to test this?
</blockquote></details>

@ksimons and I have been discussing (he reached out before submitting this PR) and I do believe it's possible. I'm working on a commit to amend this PR to add the tests.

---

**Comment by k-simons** [comment]
@bmoylan  I had a test at https://github.com/palantir/witchcraft-go-logging/pull/48/commits/380e785cbbf890cf0bb9cf15e52b11521d583d34 but it was only for a single implentation


@nmiyake  There are no span options that allow me to edit the duration and interface has private methods so I cannot create my own

**Comment by nmiyake** [comment]
@k-simons took a look, and I thought that the service loggers used the function to marshal objects, but it turns out that it doesn't, which means the approach I outlined won't work.

The alternate approach I would suggest is to add another test at wlog/trclog/trc1log/trc1logtests/tests.go:98 and test the output within the trace logging -- you'd need to perform some sleep and then assert with a bit of a range.

If that's not feasible, then I don't think you need to specifically add a test here (a test showing that we divide by 1,000 isn't really helpful without the context of the behavior)

**Comment by k-simons** [comment]
@nmiyake Ok I pushed up a test. I think this is the best that we can do given the interfaces and options available. I confirmed that the test fails when I revert the fix

**Review by bmoylan — CHANGES_REQUESTED** [review]
Just some nits!

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-:-LduFSpY1Y5MW658Ynku:bcrjtm2)* status: all files reviewed, 2 unresolved discussions (waiting on @k-simons)

___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 141 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduFNQI5Hhdg61nxHPY:-LduFNQI5Hhdg61nxHPZ:b-81mr8x) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/25ea81fe991b52bdc4c256673329a3bcfe697cca/wlog/trclog/trc1log/trc1logtests/tests.go#L141)):*
> ```Go
> 
> func getDurationValue(t *testing.T, entry logreader.Entry) int64 {
> 	for k, v := range entry {
> ```

Can we not just do `v, ok := entry["span"]`?
___
*[wlog-glog/internal/marshalers/wtracing_spanmodel.go, line 58 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-Ldtbpt_435ZT6_0yFsO:-LduErEmDctQz_Ea23RV:b6ynhrw) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/16af38a569d996e45bcb43940b9df82e6ed126e7/wlog-glog/internal/marshalers/wtracing_spanmodel.go#L58)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

I think `int64(span.Duration/time.Microsecond)` would do the same thing?
</blockquote></details>

ping, I think this reads more simply

**Comment by bmoylan** [comment]
___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 133 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduFa8o5pOwLD2sBG4l:-LduFa8o5pOwLD2sBG4m:b-1ckj21) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/25ea81fe991b52bdc4c256673329a3bcfe697cca/wlog/trclog/trc1log/trc1logtests/tests.go#L133)):*
> ```Go
> 			// Ensure the duration matches the sleep amount
> 			intValue := getDurationValue(t, entries[0])
> 			assert.True(t, intValue < 200000, "duration must be less than 200 milliseconds")
> ```

would `intValue*time.Microsecond, 200*time.Millisecond` be clearer?

**Review by nmiyake — CHANGES_REQUESTED** [review]
Can you please create this as a test separate from `jsonOutputTests`? As currently written, this adds a sleep to every JSON test case, which doesn't feel as correct. Since we're explicitly testing the timing aspect here, would prefer adding the separate function.

If this is still unclear let me know and I can push up a commit that shows the skeleton of the structure.

> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-:-LduHbHz3RalEapTyPrr:bmq2adv)* status: all files reviewed, 4 unresolved discussions (waiting on @k-simons)

___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 101 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduHJuS4-FQ3g8EOW86:-LduHJuS4-FQ3g8EOW87:bbvm3c0) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/25ea81fe991b52bdc4c256673329a3bcfe697cca/wlog/trclog/trc1log/trc1logtests/tests.go#L101)):*
> ```Go
> func JSONTestSuite(t *testing.T, loggerProvider func(w io.Writer) trc1log.Logger) {
> 	jsonOutputTests(t, loggerProvider)
> }
> ```

Please add a new function like "durationFormatOutputTest" at the same level as `jsonOutputTests`. Then, that test function should have a single test (which is pretty similar to the `Run` function) that has the sleep and asserts the duration.

**Comment by k-simons** [comment]
@bmoylan  @nmiyake addressed both CRs

**Review by k-simons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @bmoylan and @nmiyake)

___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 101 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduHJuS4-FQ3g8EOW86:-LduS5tR9hSBlDpYU8QZ:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/25ea81fe991b52bdc4c256673329a3bcfe697cca/wlog/trclog/trc1log/trc1logtests/tests.go#L101)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

Please add a new function like "durationFormatOutputTest" at the same level as `jsonOutputTests`. Then, that test function should have a single test (which is pretty similar to the `Run` function) that has the sleep and asserts the duration.
</blockquote></details>

Done.
___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 133 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduFa8o5pOwLD2sBG4l:-LduLJV6-0Lj6HstTBZM:bb6un1j) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/25ea81fe991b52bdc4c256673329a3bcfe697cca/wlog/trclog/trc1log/trc1logtests/tests.go#L133)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

would `intValue*time.Microsecond, 200*time.Millisecond` be clearer?
</blockquote></details>

Done
___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 141 at r3](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduFNQI5Hhdg61nxHPY:-LduLKCY1eXorX25FZtH:bb6un1j) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/25ea81fe991b52bdc4c256673329a3bcfe697cca/wlog/trclog/trc1log/trc1logtests/tests.go#L141)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

Can we not just do `v, ok := entry["span"]`?
</blockquote></details>

Done
___
*[wlog-glog/internal/marshalers/wtracing_spanmodel.go, line 58 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-Ldtbpt_435ZT6_0yFsO:-LduKIbn87UB9yYfaNN-:b-896fjx) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/16af38a569d996e45bcb43940b9df82e6ed126e7/wlog-glog/internal/marshalers/wtracing_spanmodel.go#L58)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

ping, I think this reads more simply
</blockquote></details>

Done

**Review by nmiyake — APPROVED** [review]
:lgtm: on my end

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-:-LduStvQAjRTXCts7H-O:bm0846x)* status: all files reviewed, 3 unresolved discussions (waiting on @bmoylan)

**Review by bmoylan — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48)* status: all files reviewed, 2 unresolved discussions (waiting on @k-simons)

___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 119 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduSdgf85M04BYyJTAU:-LduSdgf85M04BYyJTAV:b-l4527x) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/f01baa5620c56e311c91438dbcdbfa4dacf203b4/wlog/trclog/trc1log/trc1logtests/tests.go#L119)):*
> ```Go
> 	// Ensure the duration matches the sleep amount
> 	intValue := getDurationValue(t, entries[0])
> 	assert.True(t, intValue*time.Microsecond < 200*time.Millisecond, "duration must be less than 200 milliseconds")
> ```

since `assert.True` can't tell you much, you probably want the intValue included in the failure message 
___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 157 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduSod5D1nJqfKy0PAJ:-LduSod5D1nJqfKy0PAK:bgj35yj) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/f01baa5620c56e311c91438dbcdbfa4dacf203b4/wlog/trclog/trc1log/trc1logtests/tests.go#L157)):*
> ```Go
> func getDurationValue(t *testing.T, entry logreader.Entry) time.Duration {
> 	v, ok := entry["span"]
> 	assert.True(t, ok)
> ```

require.True so you don't continue if you don't find the span?

**Review by k-simons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48)* status: all files reviewed, 2 unresolved discussions (waiting on @bmoylan)

___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 119 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduSdgf85M04BYyJTAU:-LduZIWI0y1tnpYUkKwB:b-ed9g5c) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/f01baa5620c56e311c91438dbcdbfa4dacf203b4/wlog/trclog/trc1log/trc1logtests/tests.go#L119)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

since `assert.True` can't tell you much, you probably want the intValue included in the failure message 
</blockquote></details>

Sorry where?
___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 157 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduSod5D1nJqfKy0PAJ:-LduZ6wLCH3hOYnKqvMh:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/f01baa5620c56e311c91438dbcdbfa4dacf203b4/wlog/trclog/trc1log/trc1logtests/tests.go#L157)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

require.True so you don't continue if you don't find the span?
</blockquote></details>

Done.

**Review by bmoylan — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48)* status: all files reviewed, 2 unresolved discussions (waiting on @k-simons)

___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 119 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduSdgf85M04BYyJTAU:-LdufUpm6oVaboVw4qD0:bk6vrwt) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/f01baa5620c56e311c91438dbcdbfa4dacf203b4/wlog/trclog/trc1log/trc1logtests/tests.go#L119)):*
> ```
> assert.True(t, intValue*time.Microsecond < 200*time.Millisecond, "duration must be less than 200 milliseconds")
> ```
this will just print  "duration must be less than 200 milliseconds" without telling you what it got
___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 157 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduSod5D1nJqfKy0PAJ:-LdufaKv08OI3sjVSyEk:bvppjco) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/f01baa5620c56e311c91438dbcdbfa4dacf203b4/wlog/trclog/trc1log/trc1logtests/tests.go#L157)):*
<details><summary><i>Previously, k-simons wrote…</i></summary><blockquote>

Done.
</blockquote></details>

forgot to push?

**Review by k-simons — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @bmoylan and @nmiyake)

___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 119 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduSdgf85M04BYyJTAU:-LduiVcjA3evtARYdqNk:b-896fix) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/f01baa5620c56e311c91438dbcdbfa4dacf203b4/wlog/trclog/trc1log/trc1logtests/tests.go#L119)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

> ```
> assert.True(t, intValue*time.Microsecond < 200*time.Millisecond, "duration must be less than 200 milliseconds")
> ```
this will just print  "duration must be less than 200 milliseconds" without telling you what it got
</blockquote></details>

Done.
___
*[wlog/trclog/trc1log/trc1logtests/tests.go, line 157 at r4](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48#-LduSod5D1nJqfKy0PAJ:-LdujN1n2Xn1PzKf508M:bb6un1j) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/f01baa5620c56e311c91438dbcdbfa4dacf203b4/wlog/trclog/trc1log/trc1logtests/tests.go#L157)):*
<details><summary><i>Previously, bmoylan (Brad Moylan) wrote…</i></summary><blockquote>

forgot to push?
</blockquote></details>

Done

**Review by bmoylan — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/48)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
