### PR TITLE
wapp: emit event.2 event when recovering panic

### LINKED ISSUE #46: wapp: emit events on panics
cc @gdearment

### PR DESCRIPTION
**Pull request by bmoylan**
Fixes #46

This change is [Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/47)

### CODE REVIEW

**Review by nmiyake — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/47)* status: all files reviewed, 1 unresolved discussion (waiting on @bmoylan and @gdearment)

___
*[wlog/wapp/fatal.go, line 55 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-logging/47#-Lcbk7KY7BWYRlvih5_A:-Lcbk7KY7BWYRlvih5_B:b-2thb3a) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/192809c81a8f65fdfa1807289deaa50ff5476566/wlog/wapp/fatal.go#L55)):*
> ```Go
> 		}
> 		if evtlog := evt2log.FromContext(ctx); evtlog != nil {
> 			evt2log.FromContext(ctx).Event("wapp.panic_recovered",
> ```

nit: since you extract `evtlog` as a variable anyway, might as well have this as `evtlog.Event(..)`

**Review by bmoylan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/47)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @gdearment and @nmiyake)

___
*[wlog/wapp/fatal.go, line 55 at r1](https://reviewable.io/reviews/palantir/witchcraft-go-logging/47#-Lcbk7KY7BWYRlvih5_A:-Lcbms-E2XYdHbKIyfnt:b-ga8xwn) ([raw file](https://github.com/palantir/witchcraft-go-logging/blob/192809c81a8f65fdfa1807289deaa50ff5476566/wlog/wapp/fatal.go#L55)):*
<details><summary><i>Previously, nmiyake (Nick Miyake) wrote…</i></summary><blockquote>

nit: since you extract `evtlog` as a variable anyway, might as well have this as `evtlog.Event(..)`
</blockquote></details>

Whoops, that was the intention. Fixed!

**Review by nmiyake — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gdearment)

**Review by nmiyake — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/palantir/witchcraft-go-logging/47)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @gdearment)

**Pull request merged**
